export const questions = [
  // SECTION 1 - Core Personality
  {
    id: 1,
    section: "Core Personality",
    text: "When you're stressed or overwhelmed, what is your true first instinct — not what you think you should do, but what you actually do?",
    options: [
      { value: "A", label: "Pull away and try to handle it alone" },
      { value: "B", label: "Reach out to someone you trust" },
      { value: "C", label: "Distract yourself (scrolling, games, music, gym, etc.)" },
      { value: "D", label: "Get irritable or frustrated" },
      { value: "E", label: "Go into problem-solving mode immediately" },
      { value: "F", label: "Shut down emotionally" },
      { value: "G", label: "Something else" },
    ],
  },
  {
    id: 2,
    section: "Core Personality",
    text: "When something goes wrong — like a mistake, conflict, or unexpected problem — what is your internal reaction before you say or do anything?",
    options: [
      { value: "A", label: '"It\'s my fault" — you blame yourself first' },
      { value: "B", label: '"Why is this happening?" — confusion or frustration' },
      { value: "C", label: '"Okay, what\'s the plan?" — immediate strategy mode' },
      { value: "D", label: '"I need to chill for a second" — emotional pause' },
      { value: "E", label: '"This is annoying but whatever" — you detach' },
      { value: "F", label: "A mix — describe the order it happens in" },
      { value: "G", label: "Something else" },
    ],
  },
  {
    id: 3,
    section: "Core Personality",
    text: "When you're making an important decision (life choice, relationship choice, money, future, etc.), which of these describes you best?",
    options: [
      { value: "A", label: "I overthink every angle and try to predict outcomes" },
      { value: "B", label: "I go with my gut feeling" },
      { value: "C", label: "I ask other people for input" },
      { value: "D", label: "I avoid deciding until I absolutely have to" },
      { value: "E", label: "I make a plan, weigh pros/cons, then choose" },
      { value: "F", label: "I act quickly because I hate uncertainty" },
      { value: "G", label: "A mix — describe how your decision process actually works" },
    ],
  },
  {
    id: 4,
    section: "Core Personality",
    text: "When you're around people — friends, coworkers, strangers — how does your energy work?",
    options: [
      { value: "A", label: "I get energized by being around people" },
      { value: "B", label: "I enjoy people, but I need alone time to recharge" },
      { value: "C", label: "I prefer small groups or one-on-one over big groups" },
      { value: "D", label: "I can be social, but it drains me quickly" },
      { value: "E", label: "I'm quiet at first but open up once I'm comfortable" },
      { value: "F", label: "I'm outgoing with everyone" },
      { value: "G", label: "A mix — describe how your social energy actually works" },
    ],
  },
  // SECTION 2 - Emotional Landscape
  {
    id: 5,
    section: "Emotional Landscape",
    text: "When you feel hurt, disappointed, or emotionally stung by someone you care about, what do you usually do?",
    options: [
      { value: "A", label: "Shut down and go quiet" },
      { value: "B", label: "Get distant but hope they notice" },
      { value: "C", label: "Try to act normal but feel it internally" },
      { value: "D", label: "Tell them directly what bothered you" },
      { value: "E", label: "Get irritated or defensive" },
      { value: "F", label: "Overthink what happened" },
      { value: "G", label: "A mix — describe the order it happens in" },
      { value: "H", label: "Something else" },
    ],
  },
  {
    id: 6,
    section: "Emotional Landscape",
    text: "When you're upset, stressed, or emotionally heavy, how easy is it for you to identify what you're feeling?",
    options: [
      { value: "A", label: "I know exactly what I'm feeling right away" },
      { value: "B", label: "I feel something, but it takes time to understand it" },
      { value: "C", label: "I feel overwhelmed but can't name the emotion" },
      { value: "D", label: "I shut down and don't feel anything until later" },
      { value: "E", label: "I distract myself so I don't have to think about it" },
      { value: "F", label: "A mix — describe how it usually works for you" },
    ],
  },
  {
    id: 7,
    section: "Emotional Landscape",
    text: "When you're overwhelmed emotionally, which of these describes how you express it outwardly?",
    options: [
      { value: "A", label: "I look totally normal on the outside" },
      { value: "B", label: "I get quieter than usual" },
      { value: "C", label: "I get short or distant" },
      { value: "D", label: "I seem irritated even if I'm not angry" },
      { value: "E", label: "I shut down and don't talk" },
      { value: "F", label: "People can usually tell something is wrong" },
      { value: "G", label: "A mix — describe how it shows up externally" },
    ],
  },
  {
    id: 8,
    section: "Emotional Landscape",
    text: "When someone you care about is upset with you, how do you usually react internally?",
    options: [
      { value: "A", label: 'Panic — "Did I mess up?"' },
      { value: "B", label: "Guilt — you assume you did something wrong" },
      { value: "C", label: "Anxiety — you worry about losing them or disappointing them" },
      { value: "D", label: "Confusion — you don't understand what you did" },
      { value: "E", label: "Overthinking — replaying everything in your head" },
      { value: "F", label: "Emotional shutdown — you go numb" },
      { value: "G", label: "Calm — you try to understand the situation logically" },
      { value: "H", label: "A mix — describe the order it happens in" },
    ],
  },
  {
    id: 9,
    section: "Emotional Landscape",
    text: "When you're in a group setting (friends, coworkers, social events), which of these describes you best?",
    options: [
      { value: "A", label: "I stay quiet and observe until I feel comfortable" },
      { value: "B", label: "I talk, but only when someone engages me first" },
      { value: "C", label: "I can be social, but I'm not the center of attention" },
      { value: "D", label: "I'm outgoing once I warm up" },
      { value: "E", label: "I'm the one who keeps conversations going" },
      { value: "F", label: "I blend in — not loud, not silent" },
      { value: "G", label: "A mix — describe how you actually act in groups" },
    ],
  },
  // SECTION 3 - Social & Interpersonal Style
  {
    id: 10,
    section: "Social & Interpersonal Style",
    text: "When someone meets you for the first time, what do you think their first impression usually is?",
    options: [
      { value: "A", label: "Quiet or reserved" },
      { value: "B", label: "Chill and easygoing" },
      { value: "C", label: "Friendly but not overly talkative" },
      { value: "D", label: "Confident" },
      { value: "E", label: "Hard to read" },
      { value: "F", label: "Laid-back but observant" },
      { value: "G", label: "Outgoing and social" },
      { value: "H", label: "A mix — describe how people usually see you at first" },
    ],
  },
  {
    id: 11,
    section: "Social & Interpersonal Style",
    text: "When someone is talking to you — a friend, your girlfriend, a coworker — how do you usually listen?",
    options: [
      { value: "A", label: "I listen quietly and think deeply about what they're saying" },
      { value: "B", label: "I listen but I'm also thinking about what to say next" },
      { value: "C", label: "I try to understand their emotions more than their words" },
      { value: "D", label: "I focus on the facts and logic of what they're saying" },
      { value: "E", label: "I listen well but sometimes zone out if I'm tired" },
      { value: "F", label: "I give advice quickly because I want to help" },
      { value: "G", label: "A mix — describe how you actually listen" },
    ],
  },
  {
    id: 12,
    section: "Social & Interpersonal Style",
    text: "When someone tells you about their emotions — especially someone you care about — what's your natural reaction?",
    options: [
      { value: "A", label: "I try to fix it immediately" },
      { value: "B", label: "I try to understand their feelings deeply" },
      { value: "C", label: "I get anxious and worry I did something wrong" },
      { value: "D", label: "I listen quietly and let them talk" },
      { value: "E", label: "I give advice or solutions" },
      { value: "F", label: "I feel overwhelmed by their emotions" },
      { value: "G", label: "A mix — describe how you actually react" },
    ],
  },
  // SECTION 4 - Relationship & Attachment Style
  {
    id: 13,
    section: "Relationship & Attachment Style",
    text: "When you're in a relationship, which of these describes you best?",
    options: [
      { value: "A", label: "I get attached deeply and quickly" },
      { value: "B", label: "I attach slowly but strongly" },
      { value: "C", label: "I care a lot but try not to show it too much" },
      { value: "D", label: "I get anxious when I feel distance" },
      { value: "E", label: "I stay calm and steady most of the time" },
      { value: "F", label: "I need reassurance sometimes" },
      { value: "G", label: "A mix — describe how you actually attach" },
    ],
  },
  {
    id: 14,
    section: "Relationship & Attachment Style",
    text: "When you miss your significant other or feel distance in the relationship, what happens inside you?",
    options: [
      { value: "A", label: "I get anxious and start overthinking" },
      { value: "B", label: "I feel sad but try to stay calm" },
      { value: "C", label: "I distract myself so I don't spiral" },
      { value: "D", label: "I want reassurance or closeness" },
      { value: "E", label: "I try to stay logical and remind myself everything is fine" },
      { value: "F", label: "I get quiet and hope she reaches out" },
      { value: "G", label: "A mix — describe the order it happens in" },
    ],
  },
  {
    id: 15,
    section: "Relationship & Attachment Style",
    text: "When you and your significant other have a misunderstanding or tension, what do you usually do?",
    options: [
      { value: "A", label: "Try to fix it immediately" },
      { value: "B", label: "Give her space and wait for the right moment" },
      { value: "C", label: "Get anxious and want to talk right away" },
      { value: "D", label: "Shut down and hope it resolves itself" },
      { value: "E", label: "Overthink what you said or did" },
      { value: "F", label: "Stay calm but feel it internally" },
      { value: "G", label: "A mix — describe how it actually plays out" },
    ],
  },
  {
    id: 16,
    section: "Relationship & Attachment Style",
    text: "When your significant other needs space, time alone, or is busy and can't talk much, what happens inside you?",
    options: [
      { value: "A", label: "I understand it logically but still feel anxious" },
      { value: "B", label: "I get a little sad but try to stay steady" },
      { value: "C", label: "I distract myself and wait it out" },
      { value: "D", label: "I feel rejected even if I know it's not personal" },
      { value: "E", label: "I stay calm and trust everything is fine" },
      { value: "F", label: "I overthink why she needs space" },
      { value: "G", label: "A mix — describe how it actually feels for you" },
    ],
  },
  {
    id: 17,
    section: "Relationship & Attachment Style",
    text: "When your significant other expresses their own emotions — stress, sadness, frustration, insecurity — how do you feel inside?",
    options: [
      { value: "A", label: "I feel responsible for helping her" },
      { value: "B", label: "I feel pressure to fix it" },
      { value: "C", label: "I feel anxious that I might not be enough" },
      { value: "D", label: "I feel calm and supportive" },
      { value: "E", label: "I feel overwhelmed by her emotions" },
      { value: "F", label: "I feel connected and want to be there for her" },
      { value: "G", label: "A mix — describe how it actually feels inside" },
    ],
  },
  {
    id: 18,
    section: "Relationship & Attachment Style",
    text: "When you are the one feeling down, stressed, or insecure, what do you want from your significant other?",
    options: [
      { value: "A", label: "Physical closeness" },
      { value: "B", label: "Reassurance" },
      { value: "C", label: "Words of affirmation" },
      { value: "D", label: "Someone to listen" },
      { value: "E", label: "Distraction or comfort" },
      { value: "F", label: "Space to think but knowing she's there" },
      { value: "G", label: "A mix — describe what actually helps you" },
    ],
  },
  {
    id: 19,
    section: "Relationship & Attachment Style",
    text: "When your significant other pulls away emotionally (less texting, shorter responses, seems distant), what story does your mind tell you?",
    options: [
      { value: "A", label: '"She\'s busy, it\'s fine."' },
      { value: "B", label: '"Something\'s wrong but I don\'t know what."' },
      { value: "C", label: '"I must have done something."' },
      { value: "D", label: '"She needs space, I should chill."' },
      { value: "E", label: '"I\'m losing her."' },
      { value: "F", label: '"I need to fix this."' },
      { value: "G", label: "A mix — describe the order it happens in" },
    ],
  },
  {
    id: 20,
    section: "Relationship & Attachment Style",
    text: "When your significant other gives you reassurance — tells you she loves you, cares about you, or that everything is okay — what happens inside you?",
    options: [
      { value: "A", label: "Immediate relief" },
      { value: "B", label: "Temporary relief, then the thoughts come back" },
      { value: "C", label: "You feel calm and grounded" },
      { value: "D", label: "You feel loved and connected" },
      { value: "E", label: "You still overthink but less intensely" },
      { value: "F", label: "A mix — describe how it actually feels" },
    ],
  },
  {
    id: 21,
    section: "Relationship & Attachment Style",
    text: "When you imagine your ideal relationship dynamic — not fantasy, but what actually feels right for you — which of these fits best?",
    options: [
      { value: "A", label: "Close, affectionate, lots of physical connection" },
      { value: "B", label: "Supportive, steady, calm, low-drama" },
      { value: "C", label: "Best-friends energy, playful, fun" },
      { value: "D", label: "Deep emotional connection and understanding" },
      { value: "E", label: "Independence but still close" },
      { value: "F", label: "A mix — describe what your ideal actually looks like" },
    ],
  },
  // SECTION 5 - Emotional Expression
  {
    id: 22,
    section: "Emotional Expression",
    text: "When you're stressed, overwhelmed, or overthinking, what do you usually do?",
    options: [
      { value: "A", label: "Distract myself (music, games, gym, friends)" },
      { value: "B", label: "Shut down and get quiet" },
      { value: "C", label: "Talk to someone I trust" },
      { value: "D", label: "Try to solve everything in my head" },
      { value: "E", label: "Act normal on the outside but feel a lot inside" },
      { value: "F", label: "A mix — describe what actually happens" },
    ],
  },
  {
    id: 23,
    section: "Emotional Expression",
    text: "When you're upset, stressed, or hurt, how easy is it for you to express your emotions to someone else?",
    options: [
      { value: "A", label: "Very hard — I keep it inside" },
      { value: "B", label: "Hard at first, but I open up eventually" },
      { value: "C", label: "I can express it, but it takes effort" },
      { value: "D", label: "I express it easily when I trust someone" },
      { value: "E", label: "I don't express it — I just act normal" },
      { value: "F", label: "A mix — describe how it actually works for you" },
    ],
  },
  {
    id: 24,
    section: "Emotional Expression",
    text: "When you're overwhelmed emotionally, what's your default reaction?",
    options: [
      { value: "A", label: "Shut down and get quiet" },
      { value: "B", label: "Get irritated or short" },
      { value: "C", label: "Get anxious and overthink" },
      { value: "D", label: "Distract yourself" },
      { value: "E", label: "Act normal but feel a lot inside" },
      { value: "F", label: "A mix — describe what actually happens" },
    ],
  },
  {
    id: 25,
    section: "Emotional Expression",
    text: "When someone hurts your feelings — even slightly — what's your natural reaction?",
    options: [
      { value: "A", label: "I brush it off but think about it later" },
      { value: "B", label: "I get quiet and pull back" },
      { value: "C", label: "I get defensive" },
      { value: "D", label: "I pretend I'm fine but feel it inside" },
      { value: "E", label: "I confront it directly" },
      { value: "F", label: "I overthink what it means" },
      { value: "G", label: "A mix — describe what actually happens" },
    ],
  },
  {
    id: 26,
    section: "Emotional Expression",
    text: "When someone apologizes to you or tries to fix things after hurting you, what happens inside you?",
    options: [
      { value: "A", label: "I forgive quickly" },
      { value: "B", label: "I forgive but still think about it" },
      { value: "C", label: "I feel relieved" },
      { value: "D", label: "I feel appreciated and understood" },
      { value: "E", label: "I act like it's fine even if I'm still hurt" },
      { value: "F", label: "A mix — describe how it actually feels for you" },
    ],
  },
  {
    id: 27,
    section: "Emotional Expression",
    text: "When someone compliments you — your personality, your looks, your effort, your loyalty — what happens inside you?",
    options: [
      { value: "A", label: "I feel good but don't show it much" },
      { value: "B", label: "I get shy or awkward" },
      { value: "C", label: "I feel genuinely happy" },
      { value: "D", label: "I don't really believe it at first" },
      { value: "E", label: "I appreciate it deeply" },
      { value: "F", label: "A mix — describe how it actually feels for you" },
    ],
  },
  {
    id: 28,
    section: "Emotional Expression",
    text: "When you're alone with your thoughts — late at night, walking somewhere, or just chilling — what does your mind usually focus on?",
    options: [
      { value: "A", label: "The future" },
      { value: "B", label: "Relationships" },
      { value: "C", label: "Overthinking past conversations" },
      { value: "D", label: "Goals and plans" },
      { value: "E", label: "Random thoughts, daydreaming" },
      { value: "F", label: "Stress or worries" },
      { value: "G", label: "A mix — describe what actually goes on in your head" },
    ],
  },
  {
    id: 29,
    section: "Emotional Expression",
    text: "When you imagine your future self — the version of you in 5–10 years — what do you see?",
    options: [
      { value: "A", label: "Successful career" },
      { value: "B", label: "Stable relationship" },
      { value: "C", label: "Living somewhere you like" },
      { value: "D", label: "Confident, calm version of yourself" },
      { value: "E", label: "Financial stability" },
      { value: "F", label: "A mix — describe the picture you see of yourself" },
    ],
  },
  {
    id: 30,
    section: "Emotional Expression",
    text: "When you imagine yourself as a boyfriend or husband in the future, what kind of partner do you see yourself being?",
    options: [
      { value: "A", label: "Loyal and steady" },
      { value: "B", label: "Affectionate and physically close" },
      { value: "C", label: "Supportive and emotionally present" },
      { value: "D", label: "Provider — financially stable and dependable" },
      { value: "E", label: "Protective and caring" },
      { value: "F", label: "Fun, playful, best-friend energy" },
      { value: "G", label: "A mix — describe the version of you that feels right" },
    ],
  },
  // SECTION 6 - Decision Making & Personality Core
  {
    id: 31,
    section: "Decision Making & Personality Core",
    text: "When you make decisions — big or small — what do you rely on more?",
    options: [
      { value: "A", label: "Logic and thinking it through" },
      { value: "B", label: "Your gut feeling" },
      { value: "C", label: "What feels right emotionally" },
      { value: "D", label: "Advice from people you trust" },
      { value: "E", label: "A mix — describe how you actually decide things" },
    ],
  },
  {
    id: 32,
    section: "Decision Making & Personality Core",
    text: "When you're in a situation where you don't know what the right move is — relationship, school, life — what do you usually do?",
    options: [
      { value: "A", label: "Think about it alone until it makes sense" },
      { value: "B", label: "Ask someone you trust" },
      { value: "C", label: "Go with your gut" },
      { value: "D", label: "Wait and see what happens" },
      { value: "E", label: "Overthink every angle" },
      { value: "F", label: "A mix — describe what you actually do" },
    ],
  },
  {
    id: 33,
    section: "Decision Making & Personality Core",
    text: "When someone gives you criticism — even if it's meant to help — how do you react internally?",
    options: [
      { value: "A", label: "I take it personally" },
      { value: "B", label: "I get defensive at first" },
      { value: "C", label: "I think about it later and try to improve" },
      { value: "D", label: "I brush it off unless it's someone I respect" },
      { value: "E", label: "I feel it emotionally but don't show it" },
      { value: "F", label: "A mix — describe what actually happens inside you" },
    ],
  },
  {
    id: 34,
    section: "Decision Making & Personality Core",
    text: "When you're in a group — friends, coworkers, classmates — what role do you naturally fall into?",
    options: [
      { value: "A", label: "The quiet observer" },
      { value: "B", label: "The funny one" },
      { value: "C", label: "The leader" },
      { value: "D", label: "The chill, go-with-the-flow one" },
      { value: "E", label: "The one people come to for advice" },
      { value: "F", label: "A mix — describe how you actually are in groups" },
    ],
  },
  {
    id: 35,
    section: "Decision Making & Personality Core",
    text: "When you're working toward a goal — gym, school, career, relationship — what motivates you the most?",
    options: [
      { value: "A", label: "Wanting to improve yourself" },
      { value: "B", label: "Wanting to prove people wrong" },
      { value: "C", label: "Wanting to build a good future" },
      { value: "D", label: "Wanting to make someone proud" },
      { value: "E", label: "Wanting stability and success" },
      { value: "F", label: "A mix — describe what actually drives you" },
    ],
  },
  {
    id: 36,
    section: "Decision Making & Personality Core",
    text: "When you fail at something — a test, a goal, a habit, a plan — what's your natural reaction?",
    options: [
      { value: "A", label: "I get frustrated but try again" },
      { value: "B", label: "I shut down for a bit" },
      { value: "C", label: "I overthink what went wrong" },
      { value: "D", label: "I get motivated to fix it" },
      { value: "E", label: "I distract myself and come back later" },
      { value: "F", label: "A mix — describe what actually happens for you" },
    ],
  },
  {
    id: 37,
    section: "Decision Making & Personality Core",
    text: "When someone relies on you — a friend, partner, coworker — how do you usually show up?",
    options: [
      { value: "A", label: "I take it seriously and try my best" },
      { value: "B", label: "I feel pressure but still show up" },
      { value: "C", label: "I become dependable and focused" },
      { value: "D", label: "I get anxious but don't let them down" },
      { value: "E", label: "I only show up for people who matter" },
      { value: "F", label: "A mix — describe how you actually respond" },
    ],
  },
  {
    id: 38,
    section: "Decision Making & Personality Core",
    text: "When you're in a conflict — with a friend, partner, or anyone — what's your natural style?",
    options: [
      { value: "A", label: "Stay calm and try to talk it out" },
      { value: "B", label: "Get quiet and think before responding" },
      { value: "C", label: "Get emotional and want to fix it fast" },
      { value: "D", label: "Avoid conflict unless it's serious" },
      { value: "E", label: "Stand your ground if you feel disrespected" },
      { value: "F", label: "A mix — describe how you actually handle conflict" },
    ],
  },
  {
    id: 39,
    section: "Decision Making & Personality Core",
    text: "When someone you care about is upset — not at you, just upset in general — how do you naturally respond?",
    options: [
      { value: "A", label: "Try to comfort them" },
      { value: "B", label: "Give them space but stay available" },
      { value: "C", label: "Try to solve the problem" },
      { value: "D", label: "Get anxious and want to fix it fast" },
      { value: "E", label: "Act normal but stay close" },
      { value: "F", label: "A mix — describe what you actually do" },
    ],
  },
  {
    id: 40,
    section: "Decision Making & Personality Core",
    text: "When you're stressed — like really stressed — what helps you calm down the most?",
    options: [
      { value: "A", label: "Distraction (gym, games, scrolling, shows)" },
      { value: "B", label: "Talking to someone you trust" },
      { value: "C", label: "Being alone and thinking" },
      { value: "D", label: "Music or something relaxing" },
      { value: "E", label: "Working on the problem until it's solved" },
      { value: "F", label: "A mix — describe what actually helps you reset" },
    ],
  },
  {
    id: 41,
    section: "Decision Making & Personality Core",
    text: "When you're excited about something — a plan, a goal, an idea — how do you show it?",
    options: [
      { value: "A", label: "I talk about it a lot" },
      { value: "B", label: "I get energetic and motivated" },
      { value: "C", label: "I keep it inside but feel hyped" },
      { value: "D", label: "I plan everything out" },
      { value: "E", label: "I share it with someone close" },
      { value: "F", label: "A mix — describe what actually happens for you" },
    ],
  },
  {
    id: 42,
    section: "Decision Making & Personality Core",
    text: "When you imagine your ideal lifestyle — day-to-day life in the future — what does it look like?",
    options: [
      { value: "A", label: "Peaceful, stable routine" },
      { value: "B", label: "Busy, productive, always improving" },
      { value: "C", label: "Family-oriented and connected" },
      { value: "D", label: "High-energy, exciting, always doing something" },
      { value: "E", label: "Financially free and comfortable" },
      { value: "F", label: "A mix — describe the lifestyle that feels right for you" },
    ],
  },
  {
    id: 43,
    section: "Decision Making & Personality Core",
    text: "When you picture your best version of yourself — mentally, emotionally, physically — what does that version look like?",
    options: [
      { value: "A", label: "Confident and calm" },
      { value: "B", label: "Physically strong and healthy" },
      { value: "C", label: "Emotionally steady and supportive" },
      { value: "D", label: "Successful and disciplined" },
      { value: "E", label: "Socially balanced — outgoing when you want, quiet when you want" },
      { value: "F", label: "A mix — describe the version of you that feels right" },
    ],
  },
  {
    id: 44,
    section: "Decision Making & Personality Core",
    text: "When you picture yourself at your lowest — stressed, insecure, overwhelmed — what does that version of you look like?",
    options: [
      { value: "A", label: "Quiet and withdrawn" },
      { value: "B", label: "Overthinking everything" },
      { value: "C", label: "Irritable or frustrated" },
      { value: "D", label: "Distracted and unmotivated" },
      { value: "E", label: "Emotionally distant" },
      { value: "F", label: "A mix — describe what your 'low version' of you is like" },
    ],
  },
  {
    id: 45,
    section: "Decision Making & Personality Core",
    text: "When you're around new people — not close friends, just new faces — how do you naturally show up?",
    options: [
      { value: "A", label: "Quiet and observing" },
      { value: "B", label: "Friendly but reserved" },
      { value: "C", label: "Outgoing and talkative" },
      { value: "D", label: "Confident but low-key" },
      { value: "E", label: "Awkward at first but warm up later" },
      { value: "F", label: "A mix — describe how you actually act around new people" },
    ],
  },
  // SECTION 7 - Emotional Patterns & Attachment
  {
    id: 46,
    section: "Emotional Patterns & Attachment",
    text: "When you really like someone, how do you naturally show it?",
    options: [
      { value: "A", label: "Quality time" },
      { value: "B", label: "Physical affection" },
      { value: "C", label: "Doing things for them" },
      { value: "D", label: "Words and reassurance" },
      { value: "E", label: "Staying close and checking in" },
      { value: "F", label: "A mix — describe how you actually show love" },
    ],
  },
  {
    id: 47,
    section: "Emotional Patterns & Attachment",
    text: "When you miss someone you care about, what do you naturally do?",
    options: [
      { value: "A", label: "Reach out and talk to them" },
      { value: "B", label: "Get quiet and think about them" },
      { value: "C", label: "Get emotional and want closeness" },
      { value: "D", label: "Distract yourself until you see them" },
      { value: "E", label: "Feel it deeply but don't show it" },
      { value: "F", label: "A mix — describe what actually happens for you" },
    ],
  },
  {
    id: 48,
    section: "Emotional Patterns & Attachment",
    text: "When someone you care about pulls away — gets distant, busy, or less responsive — what's your natural reaction?",
    options: [
      { value: "A", label: "You get anxious and overthink" },
      { value: "B", label: "You give them space but feel it inside" },
      { value: "C", label: "You reach out more to check in" },
      { value: "D", label: "You get quiet and wait for them" },
      { value: "E", label: "You assume something's wrong" },
      { value: "F", label: "A mix — describe what actually happens for you" },
    ],
  },
  {
    id: 49,
    section: "Emotional Patterns & Attachment",
    text: "When someone gives you reassurance — tells you they care, they're not going anywhere, everything is fine — how does it hit you?",
    options: [
      { value: "A", label: "It calms you down instantly" },
      { value: "B", label: "It helps, but you still think a little" },
      { value: "C", label: "You feel relieved but still need actions" },
      { value: "D", label: "You feel loved and secure" },
      { value: "E", label: "You don't always believe it right away" },
      { value: "F", label: "A mix — describe what actually happens inside you" },
    ],
  },
  {
    id: 50,
    section: "Emotional Patterns & Attachment",
    text: "When someone you love is upset at you specifically, how do you naturally react?",
    options: [
      { value: "A", label: "You get anxious and want to fix it immediately" },
      { value: "B", label: "You get quiet and think about what you did" },
      { value: "C", label: "You get defensive at first but calm down" },
      { value: "D", label: "You apologize fast because you hate tension" },
      { value: "E", label: "You try to talk it out calmly" },
      { value: "F", label: "A mix — describe what actually happens inside you" },
    ],
  },
  {
    id: 51,
    section: "Emotional Patterns & Attachment",
    text: "When you're really vulnerable — like opening up about fears, insecurities, or deep feelings — how do you behave?",
    options: [
      { value: "A", label: "You get quiet and serious" },
      { value: "B", label: "You talk more than usual" },
      { value: "C", label: "You get emotional but stay honest" },
      { value: "D", label: "You open up only with someone you trust deeply" },
      { value: "E", label: "You struggle to express it but try anyway" },
      { value: "F", label: "A mix — describe what actually happens for you" },
    ],
  },
  {
    id: 52,
    section: "Emotional Patterns & Attachment",
    text: "When someone you love is having a bad day — not mad at you, just struggling — how do you naturally show support?",
    options: [
      { value: "A", label: "Comfort them physically (hugs, closeness)" },
      { value: "B", label: "Talk to them and listen" },
      { value: "C", label: "Try to solve the problem" },
      { value: "D", label: "Distract them with something fun" },
      { value: "E", label: "Stay close and be present" },
      { value: "F", label: "A mix — describe what you actually do" },
    ],
  },
  {
    id: 53,
    section: "Emotional Patterns & Attachment",
    text: "When you're the one having a bad day — stressed, tired, overwhelmed — how do you want the person you love to respond?",
    options: [
      { value: "A", label: "Comfort you physically (hugs, closeness)" },
      { value: "B", label: "Talk to you and listen" },
      { value: "C", label: "Give you space but stay available" },
      { value: "D", label: "Reassure you and hype you up" },
      { value: "E", label: "Distract you with something fun" },
      { value: "F", label: "A mix — describe what actually helps you feel better" },
    ],
  },
  {
    id: 54,
    section: "Emotional Patterns & Attachment",
    text: "When you imagine the perfect partner for you — not fantasy, but realistically — what qualities matter most?",
    options: [
      { value: "A", label: "Loyal and consistent" },
      { value: "B", label: "Affectionate and loving" },
      { value: "C", label: "Calm, patient, and understanding" },
      { value: "D", label: "Fun, playful, and adventurous" },
      { value: "E", label: "Supportive and encouraging" },
      { value: "F", label: "A mix — describe the qualities that actually matter to you" },
    ],
  },
  {
    id: 55,
    section: "Emotional Patterns & Attachment",
    text: "When you imagine your future self in a relationship — not fantasy, but the real you at your best — how do you want to show up as a partner?",
    options: [
      { value: "A", label: "Loyal, steady, and dependable" },
      { value: "B", label: "Affectionate, loving, and expressive" },
      { value: "C", label: "Calm, patient, and emotionally stable" },
      { value: "D", label: "Hard-working, disciplined, and protective" },
      { value: "E", label: "Fun, playful, and adventurous" },
      { value: "F", label: "A mix — describe the partner you want to become" },
    ],
  },
  // SECTION 8 - Identity, Confidence & Self-Image
  {
    id: 56,
    section: "Identity, Confidence & Self-Image",
    text: "When you think about yourself — not what others think, but your own view — which one feels the most true?",
    options: [
      { value: "A", label: "I'm confident but still working on myself" },
      { value: "B", label: "I'm self-critical but I know I have potential" },
      { value: "C", label: "I'm confident around people I trust, quieter around others" },
      { value: "D", label: "I'm a mix of confident and insecure depending on the situation" },
      { value: "E", label: "I know I'm a good person but I overthink a lot" },
      { value: "F", label: "A mix — describe how you actually see yourself deep down" },
    ],
  },
  {
    id: 57,
    section: "Identity, Confidence & Self-Image",
    text: "When people first meet you, what do you think their first impression usually is?",
    options: [
      { value: "A", label: "Quiet and calm" },
      { value: "B", label: "Confident but reserved" },
      { value: "C", label: "Chill and easygoing" },
      { value: "D", label: "Serious and focused" },
      { value: "E", label: "Friendly but not overly talkative" },
      { value: "F", label: "A mix — describe how people usually see you at first" },
    ],
  },
  {
    id: 58,
    section: "Identity, Confidence & Self-Image",
    text: "When you're fully comfortable around someone — a close friend, your girlfriend, family — how does your personality shift?",
    options: [
      { value: "A", label: "You get more talkative and playful" },
      { value: "B", label: "You get more affectionate and expressive" },
      { value: "C", label: "You get louder and more energetic" },
      { value: "D", label: "You stay calm but open up more" },
      { value: "E", label: "You become funnier and more confident" },
      { value: "F", label: "A mix — describe how you actually act when you're fully comfortable" },
    ],
  },
  {
    id: 59,
    section: "Identity, Confidence & Self-Image",
    text: "When you think about your strengths — the things you're genuinely good at — which ones feel the most true?",
    options: [
      { value: "A", label: "Being loyal and dependable" },
      { value: "B", label: "Staying calm in conflict" },
      { value: "C", label: "Being affectionate and loving" },
      { value: "D", label: "Reading people and understanding emotions" },
      { value: "E", label: "Being fun, playful, and good energy" },
      { value: "F", label: "A mix — describe the strengths you actually feel you have" },
    ],
  },
  {
    id: 60,
    section: "Identity, Confidence & Self-Image",
    text: "When you think about your weaknesses — the things you struggle with — which ones feel the most true?",
    options: [
      { value: "A", label: "Overthinking and anxiety" },
      { value: "B", label: "Struggling to express emotions directly" },
      { value: "C", label: "Getting quiet when upset" },
      { value: "D", label: "Taking things personally" },
      { value: "E", label: "Being too hard on yourself" },
      { value: "F", label: "A mix — describe the weaknesses you actually notice in yourself" },
    ],
  },
  {
    id: 61,
    section: "Identity, Confidence & Self-Image",
    text: "When you imagine the best version of yourself — the version you're trying to grow into — what does he look like?",
    options: [
      { value: "A", label: "Confident, disciplined, and stable" },
      { value: "B", label: "Loving, patient, and emotionally strong" },
      { value: "C", label: "Physically strong and healthy" },
      { value: "D", label: "Successful, focused, and driven" },
      { value: "E", label: "Calm, grounded, and unshakeable" },
      { value: "F", label: "A mix — describe the person you're becoming" },
    ],
  },
  {
    id: 62,
    section: "Identity, Confidence & Self-Image",
    text: "When you imagine how other people will describe you in the future — friends, family, your partner — what do you hope they say?",
    options: [
      { value: "A", label: "He's loyal and always there for people" },
      { value: "B", label: "He's successful and disciplined" },
      { value: "C", label: "He's loving, patient, and emotionally strong" },
      { value: "D", label: "He's fun, confident, and great to be around" },
      { value: "E", label: "He's protective, stable, and dependable" },
      { value: "F", label: "A mix — describe the reputation you want to have" },
    ],
  },
  {
    id: 63,
    section: "Identity, Confidence & Self-Image",
    text: "When you think about your social style — how you act in groups — which one feels the most true?",
    options: [
      { value: "A", label: "Quiet at first, then outgoing once comfortable" },
      { value: "B", label: "Mostly calm and observant" },
      { value: "C", label: "The funny one once you warm up" },
      { value: "D", label: "The steady, grounded presence" },
      { value: "E", label: "The one who matches the group's energy" },
      { value: "F", label: "A mix — describe how you actually act in group settings" },
    ],
  },
  {
    id: 64,
    section: "Identity, Confidence & Self-Image",
    text: "When you think about how you handle stress, which one feels the most true?",
    options: [
      { value: "A", label: "I stay calm on the outside but feel it inside" },
      { value: "B", label: "I get quiet and try to deal with it alone" },
      { value: "C", label: "I talk to someone I trust" },
      { value: "D", label: "I distract myself with activities" },
      { value: "E", label: "I push through it and keep going" },
      { value: "F", label: "A mix — describe how you actually handle stress" },
    ],
  },
  {
    id: 65,
    section: "Identity, Confidence & Self-Image",
    text: "When you think about your emotional needs in a relationship — the things that make you feel loved and secure — which ones matter most?",
    options: [
      { value: "A", label: "Physical affection (touch, closeness, cuddling)" },
      { value: "B", label: "Reassurance and verbal support" },
      { value: "C", label: "Quality time and presence" },
      { value: "D", label: "Feeling appreciated and valued" },
      { value: "E", label: "Feeling chosen and prioritized" },
      { value: "F", label: "A mix — describe what actually makes you feel loved" },
    ],
  },
  // SECTION 9 - Love Style & Relationship Behavior
  {
    id: 66,
    section: "Love Style & Relationship Behavior",
    text: "When you're in a relationship and you start to feel insecure or unsure, what do you usually do?",
    options: [
      { value: "A", label: "Get quiet and hope they notice" },
      { value: "B", label: "Ask for reassurance directly" },
      { value: "C", label: "Act normal but feel it internally" },
      { value: "D", label: "Overthink and replay everything" },
      { value: "E", label: "Pull away a little to protect yourself" },
      { value: "F", label: "A mix — describe what you actually do when you feel insecure" },
    ],
  },
  {
    id: 67,
    section: "Love Style & Relationship Behavior",
    text: "When you're really in love, how do you usually show it?",
    options: [
      { value: "A", label: "Physical affection — holding, cuddling, touching" },
      { value: "B", label: "Doing things for them — effort, favors, support" },
      { value: "C", label: "Quality time — wanting to be around them" },
      { value: "D", label: "Words — compliments, reassurance, expressing feelings" },
      { value: "E", label: "Protectiveness — making sure they're safe and okay" },
      { value: "F", label: "A mix — describe how you actually show love when you're all in" },
    ],
  },
  {
    id: 68,
    section: "Love Style & Relationship Behavior",
    text: "When your partner is upset — not at you, just upset in general — how do you usually respond?",
    options: [
      { value: "A", label: "Comfort them physically (holding, hugging, staying close)" },
      { value: "B", label: "Try to solve the problem for them" },
      { value: "C", label: "Listen quietly and let them talk" },
      { value: "D", label: "Reassure them with words" },
      { value: "E", label: "Get protective and want to fix everything" },
      { value: "F", label: "A mix — describe how you actually react when someone you love is hurting" },
    ],
  },
  {
    id: 69,
    section: "Love Style & Relationship Behavior",
    text: "When you start missing your partner, what do you usually do?",
    options: [
      { value: "A", label: "Get quiet and hope they reach out" },
      { value: "B", label: "Text them or call them" },
      { value: "C", label: "Distract yourself until it passes" },
      { value: "D", label: "Get a little clingy or affectionate" },
      { value: "E", label: "Think about them a lot but don't say anything" },
      { value: "F", label: "A mix — describe what you actually do when you miss someone you love" },
    ],
  },
  {
    id: 70,
    section: "Love Style & Relationship Behavior",
    text: "When you're in a relationship, what makes you feel most secure?",
    options: [
      { value: "A", label: "Consistent communication" },
      { value: "B", label: "Physical affection and closeness" },
      { value: "C", label: "Reassurance and honesty" },
      { value: "D", label: "Feeling prioritized and chosen" },
      { value: "E", label: "Stability and loyalty" },
      { value: "F", label: "A mix — describe what actually makes you feel safe in love" },
    ],
  },
  {
    id: 71,
    section: "Love Style & Relationship Behavior",
    text: "When you're really committed to someone, what scares you the most?",
    options: [
      { value: "A", label: "Losing them" },
      { value: "B", label: "Not being enough for them" },
      { value: "C", label: "Them losing feelings" },
      { value: "D", label: "Being taken for granted" },
      { value: "E", label: "Being lied to or betrayed" },
      { value: "F", label: "A mix — describe the fears that hit you the hardest" },
    ],
  },
  {
    id: 72,
    section: "Love Style & Relationship Behavior",
    text: "When you're in a relationship, what do you need your partner to understand about you the most?",
    options: [
      { value: "A", label: "I love deeply and need affection" },
      { value: "B", label: "I get quiet when I'm hurt" },
      { value: "C", label: "I need reassurance sometimes" },
      { value: "D", label: "I'm loyal and expect loyalty back" },
      { value: "E", label: "I overthink because I care" },
      { value: "F", label: "A mix — describe the most important things someone needs to know to love you right" },
    ],
  },
  // SECTION 10 - Conflict, Communication & Emotional Patterns
  {
    id: 73,
    section: "Conflict, Communication & Emotional Patterns",
    text: "When you're upset with your partner (not just stressed in general), how do you usually react?",
    options: [
      { value: "A", label: "Get quiet and shut down" },
      { value: "B", label: "Try to stay calm and talk it out" },
      { value: "C", label: "Act normal but feel hurt inside" },
      { value: "D", label: "Pull away a little" },
      { value: "E", label: "Get emotional and express it" },
      { value: "F", label: "A mix — describe what you actually do when you're upset with someone you love" },
    ],
  },
  {
    id: 74,
    section: "Conflict, Communication & Emotional Patterns",
    text: "When someone you love apologizes to you, what matters most for you to forgive and move on?",
    options: [
      { value: "A", label: "Their tone — it needs to feel genuine" },
      { value: "B", label: "Their actions — they need to show change" },
      { value: "C", label: "Their words — you need to hear the apology clearly" },
      { value: "D", label: "Physical closeness — a hug, touch, or being near" },
      { value: "E", label: "Time — you need a little space before you're okay" },
      { value: "F", label: "A mix — describe what actually makes you forgive" },
    ],
  },
  {
    id: 75,
    section: "Conflict, Communication & Emotional Patterns",
    text: "When you apologize to someone you love, what do you usually do?",
    options: [
      { value: "A", label: "Say it directly and clearly" },
      { value: "B", label: "Explain your feelings" },
      { value: "C", label: "Get physical — hug, hold, stay close" },
      { value: "D", label: "Try to fix the situation immediately" },
      { value: "E", label: "Get quiet but show effort through actions" },
      { value: "F", label: "A mix — describe how you actually apologize when you care" },
    ],
  },
  {
    id: 76,
    section: "Conflict, Communication & Emotional Patterns",
    text: "When someone you love is mad at you, what hurts you the most?",
    options: [
      { value: "A", label: "Them pulling away" },
      { value: "B", label: "Them not talking to you" },
      { value: "C", label: "Feeling like you disappointed them" },
      { value: "D", label: "Feeling misunderstood" },
      { value: "E", label: "Feeling like they don't care" },
      { value: "F", label: "A mix — describe what hits you the hardest" },
    ],
  },
  {
    id: 77,
    section: "Conflict, Communication & Emotional Patterns",
    text: "When you're overwhelmed emotionally, what helps you calm down the most?",
    options: [
      { value: "A", label: "Physical affection" },
      { value: "B", label: "Talking it out" },
      { value: "C", label: "Distraction" },
      { value: "D", label: "Being alone for a bit" },
      { value: "E", label: "Reassurance from someone you trust" },
      { value: "F", label: "A mix — describe what actually brings you back to center" },
    ],
  },
  {
    id: 78,
    section: "Conflict, Communication & Emotional Patterns",
    text: "When you're in a relationship, what's the one thing you absolutely won't tolerate?",
    options: [
      { value: "A", label: "Disrespect" },
      { value: "B", label: "Lying" },
      { value: "C", label: "Cheating" },
      { value: "D", label: "Being ignored" },
      { value: "E", label: "Feeling unappreciated" },
      { value: "F", label: "A mix — describe the deal-breaker that hits you the hardest" },
    ],
  },
  {
    id: 79,
    section: "Conflict, Communication & Emotional Patterns",
    text: "When you're in a relationship, what's the most important thing you give that makes you a great partner?",
    options: [
      { value: "A", label: "Loyalty" },
      { value: "B", label: "Effort" },
      { value: "C", label: "Affection" },
      { value: "D", label: "Emotional support" },
      { value: "E", label: "Honesty" },
      { value: "F", label: "A mix — describe the thing that makes you you in a relationship" },
    ],
  },
];

export const sections = [
  "Core Personality",
  "Emotional Landscape",
  "Social & Interpersonal Style",
  "Relationship & Attachment Style",
  "Emotional Expression",
  "Decision Making & Personality Core",
  "Emotional Patterns & Attachment",
  "Identity, Confidence & Self-Image",
  "Love Style & Relationship Behavior",
  "Conflict, Communication & Emotional Patterns",
];
